### ISSUE TITLE
get_twitter.py 

### ISSUE THREAD

**Issue by Sharathnasa** [striketheghong/twitter_friends_cluster#1]
@striketheghong  First of all i would like thank you for writing up this code and uploading it to the github. It will help lot of people like. I'm damn sure.

But could you please explain me on how to run this ? When i try to run get_tweets.py it ran for sometime and stopped. That is as per the code it ran for num_keys(which is lenght of owner). In my case it is 11 and stopped. 

Could you please shed some light on this.

And also what is the cluster_all and cluster_friend.py is meant for?

Please answer me asap, my project is depending on your response

Regards,
Sharath

**Comment by gina-hong** [comment]
Hey Sharath,

The code from get_twitter.py is supposed to run until the variable index reached a certain value (in my case, the end of the file).  While the calls are being made, the json result for each call is written to a file which should be accessible after it's run.  Are you getting any error messages/are you seeing any text file in your directory somewhere with some json output?

cluster_all.py was my code to run hierarchical clustering on the followers of a set of Twitter users (ex. Hillary Clinton).  The goal was to see if followers one particular user tended to cluster together more than followers of a user in a different "field" (ex. Politics vs sports).  cluster_friends.py did the same except only for the followers of a single user.  Clustering was based on looking at the number of similar users the followers had with each other (i.e. Following more of the same people would mean they were more similar Twitter users).

Let me know if you have other questions!
Best,
Gina

**Comment by Sharathnasa** [comment]
Hi Gina,

I went through the whole code. Its simply amazing! And thanks a lot for your explanation above. It did give me more insight.

I am actually getting an error while running the code on your sample dataset(Hillary Clinton). I get a NaN (infinite value) which is throwing-

```
/Users/i322865/DeepInsights/ai-engine/twitter_friends_cluster/cluster_all.py:70: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  Z = linkage(matrix, 'single', 'correlation')
Traceback (most recent call last):
  File "/Users/i322865/DeepInsights/ai-engine/twitter_friends_cluster/cluster_all.py", line 70, in <module>
    Z = linkage(matrix, 'single', 'correlation')
  File "/usr/local/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 676, in linkage
    raise ValueError("The condensed distance matrix must contain only finite values.")
ValueError: The condensed distance matrix must contain only finite values.
```

On debugging more I found that -
`len(list(users[i].values())[0]) + len(list(users[j].values())[0])` is returning **0**.

So, matrix[i][j] turns out to be **infinity**.
in this piece of code-
`matrix[i][j] = union/(len(list(users[i].values())[0]) + len(list(users[j].values())[0]))/2`

I found 0 at the following matrix indices-
```
Found denominator 0 at (5,16)
Found denominator 0 at (5,26)
Found denominator 0 at (5,30)
Found denominator 0 at (16,5)
Found denominator 0 at (16,26)
Found denominator 0 at (16,30)
Found denominator 0 at (26,5)
Found denominator 0 at (26,16)
Found denominator 0 at (26,30)
Found denominator 0 at (30,5)
Found denominator 0 at (30,16)
Found denominator 0 at (30,26)
```

Please can you help me resolve this? I tried with-
```
if len(list(users[i].values())[0]) + len(list(users[j].values())[0]) != 0:
    then do the work
```

it still throws up the error unfortunately

// @bozzmob for reference

**Comment by gina-hong** [comment]
Hmm it's odd that your fix didn't work.  Maybe it could help to setting the code to execute when the length is > 0 rather than != 0 (in case there's a type difference that makes the condition not work), and then also set the value of matrix[i][j] = 0 when that condition is met.  Another option is to do a cursory loop through the list and only keep the users where len(list(users[i].values())) >0, and then create the matrix from that set.  I can look at this more/write some code out when I'm by a computer but can't really do much testing until later today unfortunately.

**Comment by Sharathnasa** [comment]
@striketheghong  Yes, even i was thinking the same(remove off the user when the lenght is 0). I will implement this and let you know the result. 

Sure no problem. Let me know once when you do the code change.

Regards,
Sharath

**Comment by Sharathnasa** [comment]
Hi @striketheghong , Did you get a chance to take a look at the issue?
I have fixed few issues and here is my fork of it-
https://github.com/Sharathnasa/twitter_friends_cluster

Now, the error I'm getting is-
```
/Users/i322865/DeepInsights/ai-engine/twitter_friends_cluster/cluster_friends.py:58: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  Z = linkage(matrix, 'single', 'correlation')
Traceback (most recent call last):
  File "/Users/i322865/DeepInsights/ai-engine/twitter_friends_cluster/cluster_friends.py", line 58, in <module>
    Z = linkage(matrix, 'single', 'correlation')
  File "/usr/local/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 676, in linkage
    raise ValueError("The condensed distance matrix must contain only finite values.")
ValueError: The condensed distance matrix must contain only finite values.

```

Please can you take a look at it.
